import {
  NAME_FROM_BODY_REGEXES,
  ORDER_KEYWORD_REGEX,
  PHONE_REGEX,
  PREORDER_FIELD_REGEXES,
  PREORDER_FORM_MARKER,
  URL_REGEX,
} from 'src/modules/custom/order-email-processor/order-email-processor.constants';

export type PreorderFormFields = {
  email: string;
  name: string;
  phone: string | null;
  model: string | null;
};

export const subjectMentionsOrder = (subject: string | null): boolean => {
  if (!subject) return false;

  return ORDER_KEYWORD_REGEX.test(subject);
};

export const extractFirstPhone = (text: string | null): string | null => {
  if (!text) return null;
  const match = text.match(PHONE_REGEX);

  if (!match) return null;

  // Normalize: keep only digits and a leading '+'.
  const raw = match[0];
  const digits = raw.replace(/[^\d]/g, '');

  if (digits.length < 10) return null;

  return raw.startsWith('+') ? `+${digits}` : digits;
};

export const extractFirstUrl = (text: string | null): string | null => {
  if (!text) return null;
  const match = text.match(URL_REGEX);

  return match ? match[0] : null;
};

export const extractNameFromBody = (text: string | null): string | null => {
  if (!text) return null;

  for (const regex of NAME_FROM_BODY_REGEXES) {
    const match = text.match(regex);

    if (match?.[1]) return match[1].trim();
  }

  return null;
};

// Detect emails generated by the vega-preorder lander and pull the real
// customer fields out of the body. Returns null for any email that doesn't
// start with our marker or fails basic email validation — caller falls back
// to the regex/heuristic path used for human-typed orders.
export const extractPreorderFormFields = (
  text: string | null,
): PreorderFormFields | null => {
  if (!text || !text.includes(PREORDER_FORM_MARKER)) return null;

  const emailMatch = text.match(PREORDER_FIELD_REGEXES.email);
  const email = emailMatch?.[1]?.trim().toLowerCase() ?? '';

  // Cheap email shape check — full validation happens upstream in the form
  // handler, this is just a guard against malformed bodies.
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return null;

  const nameMatch = text.match(PREORDER_FIELD_REGEXES.name);
  const name = nameMatch?.[1]?.trim() ?? '';

  if (!name) return null;

  const phoneMatch = text.match(PREORDER_FIELD_REGEXES.phone);
  const rawPhone = phoneMatch?.[1]?.trim() ?? null;
  const phone = rawPhone ? normalizePhone(rawPhone) : null;

  const modelMatch = text.match(PREORDER_FIELD_REGEXES.model);
  const model = modelMatch?.[1]?.trim() || null;

  return { email, name, phone, model };
};

const normalizePhone = (raw: string): string | null => {
  const digits = raw.replace(/[^\d]/g, '');

  if (digits.length < 10) return null;

  return raw.trim().startsWith('+') ? `+${digits}` : digits;
};

// Pick a sensible name: body heuristic first, then sender's display name,
// then the local part of the email (e.g. "ivan" from "ivan@example.com").
export const pickClientName = ({
  body,
  displayName,
  email,
}: {
  body: string | null;
  displayName: string | null | undefined;
  email: string | null | undefined;
}): string => {
  const fromBody = extractNameFromBody(body);

  if (fromBody) return fromBody;

  const trimmedDisplayName = displayName?.trim();

  if (trimmedDisplayName) return trimmedDisplayName;

  if (email) {
    const localPart = email.split('@')[0] ?? email;

    return localPart;
  }

  return 'Без имени';
};
